### ISSUE TITLE
Theme::asset and Theme::secure_asset

### ISSUE THREAD

**Issue by tankerkiller125** [pingpong-labs/themes#11]
Should have Theme::asset and Theme::secure_asset just like default Laravel.

**Comment by tankerkiller125** [comment]
I have managed to get this working myself but it currently uses the config instead of the dynamic setting.

**Comment by gravitano** [comment]
Can you please create pull request, so I can add this feature for the next release of this package?

**Comment by tankerkiller125** [comment]
I can when I get the time later today. I will warn you that its currently using the "default" entry in the themes.php config. I couldn't seem to get it work with the dynamic selection.
